# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: weird-os-nvidia
# description will be included in the image's metadata
description: This is my personal OS image with NVidia drivers bundled.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos: []
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      # - google-droid-sans-fonts # Oh, no! We cannot remove this.
   
  # GNOME core apps
  - type: rpm-ostree
    install:
      - ptyxis
      - gnome-text-editor
      - loupe

  # GNOME Shell Extensions
  - type: rpm-ostree
    install:
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-gsconnect
      - nautilus-gsconnect
      - webextension-gsconnect

  # Just for convenience
  - type: rpm-ostree
    install:
      - flatseal

  # Fonts
  - type: rpm-ostree
    install:
      - cascadia-code-fonts
      - cascadia-mono-fonts
    remove:
      - open-sans-fonts
      - adobe-source-code-pro-fonts

  # We have removed Source Code Pro, so we have to make a substitute.
  - type: gschema-overrides
    include:
      - zz1-monospace-font.gschema.override
      - zz1-enabled-extensions.gschema.override

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - com.mattjakeman.ExtensionManager
        - io.github.celluloid_player.Celluloid
        - org.gnome.Evince
        - org.gnome.SimpleScan
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
        - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

