# image will be published to ghcr.io/<user>/<name>
name: weird-os-nvidia
# description will be included in the image's metadata
description: This is my personal OS image with NVidia drivers bundled.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: akmods # Various kernel modules.
    install:
      - v4l2loopback
      - wl
      - evdi

  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.
  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
      - gnome-console
      - virt-manager
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - gnome-terminal
      - gnome-terminal-nautilus
      # - google-droid-sans-fonts # Oh, no! We cannot remove this.

  # GNOME Shell Extensions
  - type: rpm-ostree
    install:
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-gsconnect
      - nautilus-gsconnect
      - webextension-gsconnect

  # Fonts
  - type: rpm-ostree
    install:
      - cascadia-code-fonts
      - cascadia-mono-fonts
    remove:
      - open-sans-fonts
      - adobe-source-code-pro-fonts

  # We have removed Source Code Pro, so we have to make a substitute.
  - type: gschema-overrides
    include:
      - zz1-monospace-font.gschema.override
      - zz1-enabled-extensions.gschema.override

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.mozilla.firefox
        - org.gnome.TextEditor
        - com.mattjakeman.ExtensionManager
        - org.gnome.Loupe
        - io.github.celluloid_player.Celluloid
        - com.github.tchx84.Flatseal
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
        - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

